server:
  port: 8082

spring:
  datasource:
    # appointment-service owns its own database, created on first connect
    url: jdbc:mysql://localhost:3306/appointment_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info